project:
  type: website
  output-dir: docs

website:
  title: "University of Pretoria Workshop"
  repo-url: https://github.com/JeffreyRacine/UPworkshop
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Information
      - topics.qmd
      - about.qmd
      - lab.qmd
    logo: avatar.png
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/JeffreyRacine/UPworkshop
          - text: Report a Bug
            url:  https://github.com/JeffreyRacine/UPworkshop/issues
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    code-tools:
      source: repo

editor: visual
